### ISSUE TITLE
Objects (e.g. helicopter) don't move

### ISSUE THREAD

**Issue by ambiente1** [rehlds/resemiclip#1]
Hey!

We're using Resemiclip on our CS1.6-Servers but have an issue with a mod called "Zombie Escape".

When two or more players of the same team jump into the saving helicopter it starts moving (until the map goal is reached), but if they stands to close together (one player on same position as another player (both same team)), the helicopter doesn't move anymore.

For that scenario some people remake the cs_team_semiclip.sma for these mods.

Maybe this could be included to Resemiclip itself?

**Comment by justgo97** [comment]
you can use sv_force_ent_intersection instead.

**Comment by ambiente1** [comment]
Thanks @justgo97 - working!

**Comment by justgo97** [comment]
np, if solved close the issue.
