### ISSUE TITLE
Cars can't be driven

### ISSUE THREAD

**Issue by Arxero** [rehlds/resemiclip#3]
Hey!
I am using ReSemiclip version 2.3.9 on my server [Awesome Cars + Fun Maps](http://awesomecs.syntrwave.com/) with the latest **ReGameDLL_CS**, and **ReHLDS** running on Linux with server crvar **sv_force_ent_intersection** set to **1**
And since recently cars can't be driven at all, more on what I am talking about in [this short clip](https://d1playscdntv-a.akamaihd.net/video/HTPtXVdNlnm/processed/720.mp4) or in [this one](https://d1playscdntv-a.akamaihd.net/video/HTbiisRXRsl/processed/720.mp4)
We have tested: 
2.2 version with the original GameDLL
2.2 version with the latest ReGameDLL
2.3.9 version with the latest ReGameDLL
2.3.9 version with the 222 ReGameDLL
And nothing seems to work, the problem is just like this previous issue I saw here.(https://github.com/rehlds/resemiclip/issues/1)
I would be glad see if you find a way of fixing it, Thank you!

**Comment by s1lentq** [comment]
what is your version rehlds?

**Comment by Arxero** [comment]
The hosting told me I am on the last version of ReHLDS, btw we tested it now with your latest update [here](https://github.com/dreamstalker/rehlds/commit/690296605f9423000024d439025811c47464f0a6) and seems to be working just fine, just like before. And you man deserve a cookie for acting so fast on it. 🥇
